
language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest.cov
script:
  - python -m pytest --cov app

after_success:
  - coveralls
